<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/config/config.php';
require_once dirname(__DIR__) . '/config/database.php';
require_once __DIR__ . '/helpers.php';

function pmr_php_requirements(): array
{
    $checks = [];
    $checks[] = [
        'label' => 'PHP ' . PMR_MIN_PHP . '+ (this server: ' . PHP_VERSION . ')',
        'ok' => version_compare(PHP_VERSION, PMR_MIN_PHP, '>='),
    ];
    foreach (['pdo', 'pdo_mysql', 'mbstring', 'json', 'session', 'filter', 'openssl'] as $ext) {
        $checks[] = ['label' => 'Extension: ' . $ext, 'ok' => extension_loaded($ext)];
    }
    $lockDir = dirname(PMR_INSTALL_LOCK);
    $checks[] = [
        'label' => 'install/ directory is writable',
        'ok' => is_dir($lockDir) && is_writable($lockDir),
    ];
    $uploads = PMR_BASE_PATH . DIRECTORY_SEPARATOR . 'uploads';
    if (!is_dir($uploads)) {
        @mkdir($uploads, 0755, true);
    }
    $checks[] = [
        'label' => 'uploads/ directory is writable',
        'ok' => is_dir($uploads) && is_writable($uploads),
    ];
    $rootWritable = is_writable(PMR_BASE_PATH);
    $envExists = is_file(PMR_BASE_PATH . DIRECTORY_SEPARATOR . '.env');
    $checks[] = [
        'label' => '.env can be created in site root (or already exists)',
        'ok' => $envExists || $rootWritable,
    ];
    return $checks;
}

function pmr_requirements_ok(array $checks): bool
{
    foreach ($checks as $check) {
        if (!$check['ok']) {
            return false;
        }
    }
    return true;
}

function pmr_write_env_file(array $data): void
{
    $path = PMR_BASE_PATH . DIRECTORY_SEPARATOR . '.env';
    $escape = static function (string $value): string {
        if (str_contains($value, ' ') || str_contains($value, '#') || str_contains($value, '"')) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
        }
        return $value;
    };
    $lines = [
        '# Generated by /install/ on ' . gmdate('c') . '. Do not commit.',
        'APP_NAME=' . $escape((string) ($data['APP_NAME'] ?? 'PMRatnam')),
        'APP_ENV=production',
        'APP_DEBUG=false',
        'APP_URL=' . $escape((string) ($data['APP_URL'] ?? '')),
        '',
        'DB_HOST=' . $escape((string) ($data['DB_HOST'] ?? 'localhost')),
        'DB_PORT=' . $escape((string) ($data['DB_PORT'] ?? '3306')),
        'DB_NAME=' . $escape((string) ($data['DB_NAME'] ?? '')),
        'DB_USER=' . $escape((string) ($data['DB_USER'] ?? '')),
        'DB_PASS=' . $escape((string) ($data['DB_PASS'] ?? '')),
        'DB_CHARSET=utf8mb4',
        '',
        'SESSION_NAME=pmratnam_admin',
        'SESSION_LIFETIME=28800',
        '',
    ];
    if (!empty($data['DB_SOCKET'])) {
        $lines[] = 'DB_SOCKET=' . $escape((string) $data['DB_SOCKET']);
        $lines[] = '';
    }
    $ok = file_put_contents($path, implode("\n", $lines) . "\n", LOCK_EX);
    if ($ok === false) {
        throw new RuntimeException('Could not write .env. On Hostinger, create the file in public_html and set permissions to 600.');
    }
    @chmod($path, 0600);
}

function pmr_split_sql_statements(string $sql): array
{
    $sql = preg_replace('/^\s*--.*$/m', '', $sql) ?? $sql;
    $parts = preg_split('/;\s*$/m', $sql) ?: [];
    $out = [];
    foreach ($parts as $part) {
        $stmt = trim($part);
        if ($stmt === '') {
            continue;
        }
        $out[] = $stmt;
    }
    return $out;
}

function pmr_should_skip_schema_statement(string $stmt): bool
{
    $normalized = strtoupper(ltrim($stmt));
    return str_starts_with($normalized, 'CREATE DATABASE') || str_starts_with($normalized, 'USE ');
}

function pmr_run_schema(PDO $pdo): void
{
    $file = PMR_BASE_PATH . DIRECTORY_SEPARATOR . 'database' . DIRECTORY_SEPARATOR . 'schema.sql';
    if (!is_readable($file)) {
        throw new RuntimeException('database/schema.sql is missing.');
    }
    $sql = file_get_contents($file);
    if ($sql === false) {
        throw new RuntimeException('Could not read database/schema.sql.');
    }
    foreach (pmr_split_sql_statements($sql) as $stmt) {
        if (pmr_should_skip_schema_statement($stmt)) {
            continue;
        }
        $pdo->exec($stmt);
    }
}

function pmr_mark_installed(PDO $pdo): void
{
    $pdo->prepare(
        'INSERT INTO settings (setting_group, setting_key, setting_value)
         VALUES (\'install\', \'install.complete\', \'1\')
         ON DUPLICATE KEY UPDATE setting_value = \'1\''
    )->execute();

    $pdo->prepare(
        'INSERT INTO seo_settings (id, site_name, default_meta_title, default_meta_description)
         VALUES (1, ?, ?, ?)
         ON DUPLICATE KEY UPDATE site_name = VALUES(site_name)'
    )->execute([
        'PMRatnam',
        'PMRatnam | Digital Marketing',
        'Digital marketing, web development, and branding services in Hyderabad.',
    ]);

    $written = file_put_contents(PMR_INSTALL_LOCK, 'installed ' . gmdate('c') . "\n", LOCK_EX);
    if ($written === false) {
        throw new RuntimeException('Schema imported but lock file could not be written.');
    }
}

function pmr_create_first_admin(PDO $pdo, string $name, string $email, string $password): int
{
    $email = strtolower(trim($email));
    $name = trim($name);
    if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new InvalidArgumentException('Enter a valid name and email.');
    }
    if (strlen($password) < 12) {
        throw new InvalidArgumentException('Password must be at least 12 characters.');
    }

    $count = (int) $pdo->query('SELECT COUNT(*) FROM admins')->fetchColumn();
    if ($count > 0) {
        throw new RuntimeException('An admin user already exists.');
    }

    $hash = password_hash($password, PASSWORD_DEFAULT);
    if (!is_string($hash)) {
        throw new RuntimeException('Could not hash the password.');
    }

    $stmt = $pdo->prepare(
        'INSERT INTO admins (name, email, password_hash, role, status) VALUES (?, ?, ?, \'super_admin\', \'active\')'
    );
    $stmt->execute([$name, $email, $hash]);
    return (int) $pdo->lastInsertId();
}

function pmr_test_db_credentials(string $host, string $port, string $name, string $user, string $pass, ?string $socket = null): PDO
{
    $pdo = pmr_pdo_connect_without_db($host, $port, $user, $pass, $socket);
    $quoted = str_replace('`', '``', $name);
    $pdo->exec('USE `' . $quoted . '`');
    return $pdo;
}
